#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

# Ubuntu machines.
cookbook 'apt'

# LAMP stack.
cookbook 'mysql'
cookbook 'apache2'
cookbook 'php'

# Misc.
cookbook 'database'
cookbook 'git'

# Our forks of contributed cookbooks.
cookbook 'drush',
  :github => "msonnabaum/chef-drush",
  :ref => "master"
